name: Hrz.Operations.Resulting-CI

on:
  pull_request:
    pull_request: [ "main", "rc/v*", "release/v*" ]

jobs:
  build:
    name: Build stage
    uses: ./.github/workflows/build.yml
  
  test:
    name: Test stage
    needs: [ build ]
    uses: ./.github/workflows/test.yml